proxy:
  url: https://free-proxy-list.net/
  output_filename: proxies.json

goodreads:
  url: https://goodreads.com
  proxy_filename: proxies.json
  genres:
    - fantasy
  custom_settings:
    DOWNLOADER_MIDDLEWARES:
      rotating_proxies.middlewares.RotatingProxyMiddleware: 610
    ITEM_PIPELINES:
      src.pipelines.book_info_writer.BookInfoWriterPipeline: 1
      scrapy.pipelines.images.ImagesPipeline: 2
    RETRY_TIMES: 10
    DOWNLOAD_TIMEOUT: 20
    CONCURRENT_REQUESTS_PER_DOMAIN: 2
    ROTATING_PROXY_PAGE_RETRY_TIMES: 10
    ROTATING_PROXY_LOGSTATS_INTERVAL: 20
    IMAGES_STORE: .
