proxy:
  url: "https://free-proxy-list.net/"
  output_filename: "proxies.json"
useragent:
  url: "http://useragentstring.com/pages/useragentstring.php?name=Chrome"
  output_filename: "useragents.json"
goodreads:
  url: "https://goodreads.com"
  proxy_filename: "proxies.json"
  useragents_filename: "useragents.json"
  custom_settings:
    DOWNLOADER_MIDDLEWARES:
      rotating_proxies.middlewares.RotatingProxyMiddleware: 610
    DOWNLOAD_TIMEOUT: 20
    CONCURRENT_REQUESTS_PER_DOMAIN: 2
    RETRY_TIMES: 10
    ROTATING_PROXY_PAGE_RETRY_TIMES: 10
    ROTATING_PROXY_LOGSTATS_INTERVAL: 20
    ITEM_PIPELINES:
      pipelines.book_info_writer.BookInfoWriterPipeline: 1
      scrapy.pipelines.images.ImagesPipeline: 2
    IMAGES_STORE: .
