class Constants:
    CONFIG_KEY_PROXY = "PROXY"
    CONFIG_KEY_OUTPUT_FILENAME = "OUTPUT_FILENAME"
    CONFIG_KEY_GOODREADS = "GOODREADS"
    CONFIG_KEY_URL = "URL"
    CONFIG_KEY_GENRES = "GENRES"
    CONFIG_KEY_OUTPUT_TO = "OUTPUT_TO"
    CONFIG_KEY_OUTPUT_TYPE = "OUTPUT_TYPE"
    CONFIG_KEY_FILENAME = "FILENAME"
    CONFIG_KEY_DELIMITER = "DELIMITER"
    KEY_GENRE_BASE_URL = "genre_base_url"
    KEY_GENRE_TITLE = "genre_title"
    KEY_ROTATING_PROXY_LIST = "ROTATING_PROXY_LIST"
    SELECTOR_PROXY_LIST_ROW = "table[id=proxylisttable] tbody tr"
    SELECTOR_PROXY_INFO = "td::text"
    SELECTOR_GENRE_PAGINATION = "div[class=pagination] a::text"
    SELECTOR_GENRE_TITLE = "div[class=genreHeader] h1[class=left]::text"
    SELECTOR_BOOK_TITLE = "h1[id=bookTitle]::text"
    SELECTOR_BOOK_AUTHOR = "a[class=authorName] span[itemprop=name]::text"
    SELECTOR_BOOK_RATING = "span[itemprop=ratingValue]::text"
    SELECTOR_BOOK_COVER_ENLARGE = "div[class=editionCover] img::attr(src)"
    SELECTOR_BOOK_SERIES = "h2[id=bookSeries] a::text"
    SELECTOR_BOOK_DESCRIPTION_LONG = "div[id=description] span[id=freeText{data_text_id}]"
    SELECTOR_BOOK_DESCRIPTION_SHORT = "div[id=description] span"
    SELECTOR_BOOK_FORMAT = "span[itemprop=bookFormat]::text"
    SELECTOR_BOOK_PAGES = "span[itemprop=numberOfPages]::text"
    SELECTOR_BOOK_ISBN = "span[itemprop=isbn]::text"
    SELECTOR_BOOK_ASIN = "div[itemprop=isbn]::text"
    SELECTOR_BOOK_PUBLISH_INFO = "div[id=details] div[class=row]::text"
    SELECTOR_BOOK_EDITION = "span[itemprop=bookEdition]::text"
    SELECTOR_BOOK_EDITION_LANGUAGE = "div[itemprop=inLanguage]::text"
    SELECTOR_DATA_TEXT_ID = "div[id=description] a::attr(data-text-id)"
    REGEX_GENRES_URL = r"/genres/+"
    REGEX_GENRES_BOOKLIST_URL = r"/list/show/+"
    REGEX_GENRES_BOOKLIST_BOOK_URL = r"/book/show/+"
    ITEM_FIELD_GENRE = "genre"
    ITEM_FIELD_TITLE = "title"
    ITEM_FIELD_AUTHOR = "author"
    ITEM_FIELD_RATING = "rating"
    ITEM_FIELD_DESCRIPTION = "description"
    ITEM_FIELD_SERIES = "series"
    ITEM_FIELD_BOOK_FORMAT = "book_format"
    ITEM_FIELD_PAGES = "pages"
    ITEM_FIELD_ISBN = "isbn"
    ITEM_FIELD_PUBLISH_INFO = "publish_info"
    ITEM_FIELD_PUBLISHER = "publisher"
    ITEM_FIELD_PUBLISH_DATE = "publish_date"
    ITEM_FIELD_EDITION = "edition"
    ITEM_FIELD_EDITION_LANGUAGE = "edition_language"
    ITEM_FIELD_IMAGE_URLS = "image_urls"
    HTML_REGEX = "<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});"
    OUTPUT_TYPE_CSV = "csv"
    OUTPUT_TYPE_MONGO = "mongo"
    OUTPUT_TYPE_DRIVE = "drive"
    OUTPUT_TYPE_GCS = "gcs"
