class Constants:
    KEY_PROXY = "proxy"
    KEY_USERAGENT = "useragent"
    KEY_GOODREADS = "goodreads"
    KEY_URL = "url"
    KEY_OUTPUT_FILENAME = "output_filename"
    KEY_PROXY_FILENAME = "proxy_filename"
    KEY_CUSTOM_SETTINGS = "custom_settings"
    KEY_GENRE_BASE_URL = "genre_base_url"
    KEY_GENRES = "genres"
    KEY_ROTATING_PROXY_LIST = "ROTATING_PROXY_LIST"
    SELECTOR_PROXY_LIST_ROW = "table[id=proxylisttable] tbody tr"
    SELECTOR_PROXY_INFO = "td::text"
    SELECTOR_GENRE_PAGINATION = "div[class=pagination] a::text"
    SELECTOR_BOOK_TITLE = "h1[id=bookTitle]::text"
    SELECTOR_BOOK_AUTHOR = "a[class=authorName] span[itemprop=name]::text"
    SELECTOR_BOOK_RATING = "span[itemprop=ratingValue]::text"
    SELECTOR_BOOK_COVER_ENLARGE = "div[class=editionCover] img::attr(src)"
    SELECTOR_BOOK_SERIES = "h2[id=bookSeries] a::text"
    SELECTOR_BOOK_DESCRIPTION_LONG = "div[id=description] span[id=freeText{data_text_id}]"
    SELECTOR_BOOK_DESCRIPTION_SHORT = "div[id=description] span"
    SELECTOR_DATA_TEXT_ID = "div[id=description] a::attr(data-text-id)"
    REGEX_GENRES_URL = r"/genres/+"
    REGEX_GENRES_BOOKLIST_URL = r"/list/show/+"
    REGEX_GENRES_BOOKLIST_BOOK_URL = r"/book/show/+"
    ITEM_FIELD_TITLE = "title"
    ITEM_FIELD_AUTHOR = "author"
    ITEM_FIELD_RATING = "rating"
    ITEM_FIELD_DESCRIPTION = "description"
    ITEM_FIELD_SERIES = "series"
    ITEM_FIELD_IMAGE_URLS = "image_urls"
    HTML_REGEX = "<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});"
